// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
