// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo():Promise<Record<string, any>>;

export function GetLogPath():Promise<string>;

export function GetServerURL():Promise<string>;

export function OpenLogFile():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;
